### ISSUE TITLE
Whether the library can be used for Android？

### ISSUE THREAD

**Issue by tianshaokai** [opencollab/jlatexmath#44]

**Comment by darshantejani007** [comment]
Have you found anything? @tianshaokai

**Comment by murkle** [comment]
This is a port of JLaTeXMath to Android:
https://github.com/geogebra/geogebra/tree/master/retex/renderer-android

**Comment by sylvestre** [comment]
Too bad it wasn't merged in the main branch

**Comment by davidmoten** [comment]
What parts of JLatexMath are not supported on Android?

**Comment by murkle** [comment]
It compiles across html5 (web) / iOS / Android and Java JRE (desktop) environments.

Basically everything works. We've removed \includegraphics as that doesn't make sense for web so we've added this instead

`\imagebasesixtyfour{40}{36}{data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAkCAIAAAB0Xu9BAAAAKUlEQVR42u3NMQEAAAwCIPuX1hbbAwVIn0QsFovFYrFYLBaLxWKx+M4AoNrQEWa6zscAAAAASUVORK5CYII=}`

Apart from the cross-platform refactoring it's also been improved to use Enums instead of Reflection. It's also had the clone() stuff removed for GWT compatibility.

We've added \cellcolor, I think that hasn't been added to this fork yet:
https://github.com/opencollab/jlatexmath/issues/25

You can try it here:
https://www.geogebra.org/m/RC7Pnnk5

**Comment by davidmoten** [comment]
Thanks @murkle. Would it make sense to contribute those changes back to this project?

**Comment by murkle** [comment]
From the users' point of view: yes, definitely

I'm not sure the best way to do it though as the structure is obviously very different in some respects.

The good news is that it's been very well tested by tens of millions of users so I'm confident we haven't introduced new bugs :)

Here's a minimal example of the HTML5 library:
http://test.geogebra.org/~mike/jlm/inlineTest.html

**Comment by murkle** [comment]
Also we've switched all "float" -> "double" as float doesn't exist in JavaScript/HTML5

**Comment by tianshaokai** [comment]
How does the latex formula automatically display in Android?
