### ISSUE TITLE
Text-only or MathML rendering of parsed TeXFormula

### ISSUE THREAD

**Issue by cosimo** [opencollab/jlatexmath#72]
First of all, thanks for jlatexmath!

I'm trying to use the TeXFormula and TeXParser classes to generate a "linear" version of the expression, for rendering in text-only contexts like CSV files or terminal/console, or even MathML/OOML.

Do you know if this has been done before using jlatexmath? It seems weird that I'm the first to attempt such a task, but somehow I can't find any evidence of this having been done. Microsoft Office has this capability: Excel provides fallback versions of any equation objects added to the spreadsheets and Libreoffice can display them (using the fallback version).

I tried to extend the TeXParser class to get access to the parsed Atoms and output a text version, but most members are private. I could start working on a PR for that if you think it'd be useful, but as I said, do you think it's a worthy approach, or know if it's been done before?

Would appreciate any suggestions.

**Comment by calixteman** [comment]
Firstly, you should use experimental branch of this project: afaik, geogebra project uses it so I guess it's pretty stable.
Secondly, I think you could add a method `toMathML` or something like that in each Atom to convert it into mathml or whatever.
For example, in `FractionAtom.java`, we've almost everything (num, den, thickness, ...) to be able to dump it into mathml.
So you could add this method in `Atom.java` as abstract and then implement it for each Atom.
If some Atoms are missing, then feel free to add them.
From my pov it should be a way easier to work at Atom level rather to work around the parser because Atoms doesn't contain any layout stuff but just the basic structural info.

**Comment by murkle** [comment]
It's already done for "flat" syntax, see https://github.com/opencollab/jlatexmath/blob/experimental/jlatexmath/src/main/java/org/scilab/forge/jlatexmath/share/serialize/TeXAtomSerializer.java

Adapting to export MathML should be straightforward I think 😎

**Comment by calixteman** [comment]
@murkle, you should rewrite that stuff... all these `instanceof` aren't really OOP. I think adding an abstract method `serialize` in `Atom.java` would be nicer.
Anyway, just my two cents...

**Comment by murkle** [comment]
Well, there's some advantage to having it all in one place (especially when we have two versions not quite in sync :)
